version: 2
registries:
  npm-registry-npm-fontawesome-com:
    type: npm-registry
    url: https://npm.fontawesome.com
    token: "${{secrets.NPM_REGISTRY_NPM_FONTAWESOME_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:59"
    timezone: Asia/Singapore
  open-pull-requests-limit: 10
  reviewers:
  - geraldyeo
  ignore:
  - dependency-name: gatsby-source-contentful
    versions:
    - 2.3.49
    - 5.0.3
    - 5.1.0
    - 5.1.2
    - 5.2.0
    - 5.2.1
    - 5.3.0
  - dependency-name: gatsby
    versions:
    - 2.30.2
    - 2.31.1
    - 2.32.10
    - 2.32.3
    - 2.32.5
    - 2.32.8
    - 3.0.4
    - 3.1.1
    - 3.1.2
    - 3.2.1
    - 3.3.0
    - 3.3.1
  - dependency-name: eslint
    versions:
    - 7.17.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: concurrently
    versions:
    - 5.3.0
    - 6.0.0
    - 6.0.1
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.1.1
    - 5.1.3
    - 5.2.0
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.5
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
  registries:
  - npm-registry-npm-fontawesome-com
