# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

_defaults: &defaults
  working_directory: &working_directory ~/foostack-monorepo
  docker:
    - image: circleci/node:lts

_run:
  node: &node
    command: yarn install

jobs:
  build:
    <<: *defaults

    steps:
      - checkout
      - restore_cache:
          keys:
            - ci-dependencies-{{ checksum "package.json" }}
            - ci-dependencies-
      - run: *node
      - save_cache:
          key: ci-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: yarn run build
      - persist_to_workspace:
          root: *working_directory
          paths:
            - node_modules

  test:
    <<: *defaults

    steps:
      - checkout
      - attach_workspace:
          at: *working_directory
      - run: yarn test

workflows:
  version: 2
  build-test:
    jobs:
      - build:
          context: Contentful
      - test:
          requires:
            - build
