# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

_defaults: &defaults
  working_directory: &working_directory ~/foostack-monorepo
  docker:
    - image: circleci/node:lts

_run:
  node: &node
    name: Install Dependencies
    command: yarn install --frozen-lockfile

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-
      - run: *node
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn run build
      - persist_to_workspace:
          root: *working_directory
          paths:
            - node_modules

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: *working_directory
      - run: yarn run test:coverage
      - persist_to_workspace:
          root: *working_directory
          paths:
            - node_modules
            - coverage

  codacy-coverage:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: *working_directory
      - run: yarn run test:codacy-coverage

workflows:
  version: 2
  build-test:
    jobs:
      - build: # job runs for all branches and all tags.
          context: dev-foostack
          filters:
            tags:
              only: /.*/
      - test: # job runs for all branches and all tags.
          context: dev-foostack
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - codacy-coverage: # job runs for no branches and only for tags starting with ‘v’.
          context: dev-foostack
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
